# Generated by Django 5.1.7 on 2025-05-02 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_modelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
    ]
