# Generated by Django 5.1.7 on 2025-05-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='categoria',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
