# Generated by Django 5.1.7 on 2025-05-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_modelo_categoria_alter_modelo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='categoria',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
